trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  - group: fabric-cicd-vars

stages:
  - stage: DeployToDev
    displayName: 'Deploy to Dev Workspace'
    jobs:
      - job: DeployDev
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.11'
          - script: |
              pip install fabric-cicd azure-identity
          - task: PythonScript@0
            inputs:
              scriptPath: 'Workspace_Data/Fabric_Data/auth_spn_secret_AzDo.py'
              arguments: >
                --WorkspaceId $(DevWorkspaceId)
                --Environment "Dev"
                --RepositoryDirectory "$(Build.SourcesDirectory)/Workspace_Data/Fabric_Data"
                --ItemsInScope $(ItemsInScope)
                --ClientId $(ClientId)
                --ClientSecret $(ClientSecret)
                --TenantId $(TenantId)

